# Generated by Django 3.1.6 on 2021-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipelabel', models.CharField(max_length=100)),
                ('recipeimage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('recipeingredient1', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient2', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient3', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient4', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient5', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient6', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient7', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient8', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient9', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient10', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient11', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient12', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient13', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient14', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient15', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient16', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient17', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient18', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient19', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient20', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient21', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient22', models.CharField(blank=True, max_length=100, null=True)),
                ('recipeingredient23', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
