# Generated by Django 3.1.6 on 2021-03-15 14:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient10',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient11',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient12',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient13',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient14',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient15',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient16',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient17',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient18',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient19',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient2',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient20',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient21',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient22',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient23',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient3',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient4',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient5',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient6',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient7',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient8',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient9',
        ),
        migrations.AlterField(
            model_name='recipefood',
            name='recipeingredient1',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=25), size=25),
        ),
    ]
