# Generated by Django 3.1.6 on 2021-03-15 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0003_delete_recipefood'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipelabel', models.CharField(max_length=100)),
                ('recipeimage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('recipeingredient1', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
            ],
        ),
    ]
