# Generated by Django 3.1.6 on 2021-03-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipefood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeingredient1',
        ),
        migrations.AlterField(
            model_name='recipefood',
            name='recipeimage',
            field=models.ImageField(blank=True, null=True, upload_to='imagerecipe'),
        ),
    ]
