# Generated by Django 3.1.6 on 2021-03-15 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20210315_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipefood',
            name='recipeingredient1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
