# Generated by Django 3.1.7 on 2021-03-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20210316_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipefood',
            name='recipeimage',
        ),
        migrations.AddField(
            model_name='recipefood',
            name='recipecalories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
