# Generated by Django 3.1.6 on 2021-03-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210313_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
